### PR TITLE
support for bridging services

### PR DESCRIPTION
**Pull request by dirk-thomas**
This will replace #36. I have tried to keep the history of the previous PR (without the tests yet). Based on that I have resolved the merge conflicts (due to #44) and made it compile again. I haven't yet spend the time to test the bridge or refactor the code to avoid various duplication (search for `TODO(dirk-thomas)`).

### CODE REVIEW

**Comment by dhood** [comment]
@dirk-thomas the second commit in #36 wasn't just adding tests, it was also addressing comments from a review of yours. as a result, this new PR doesn't seem to fully capture all of the work that was in #36, as https://github.com/ros2/ros1_bridge/pull/36/commits/84f02e72ad6c92ba10aaaf9d692ed92cd36fd79a had already addressed some of the TODOs you are referring to

I am not saying that you should rebase the second commit, but I wanted to point out in case it was something you weren't aware of

**Comment by dirk-thomas** [comment]
Good point. I will try to manually merge them when I get back to this.

**Comment by dhood** [comment]
ok. we can then add the "connects to ros2/examples#136" tag too

**Comment by haueck** [comment]
I added one more commit to the https://github.com/ros2/ros1_bridge/pull/36. I can rebase my fork with ros2/ros1_bridge/master and it will be possible to merge my pull request without any conflicts. Maybe it will be easier that way, what do you think?

**Pull request closed without merging**
