### PR TITLE
Drop workaround for Fast-RTPS typesupport issue 

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says. To be tested and merged along with https://github.com/ros2/rmw_fastrtps/pull/342.

### CODE REVIEW

**Comment by hidmic** [comment]
CI up to `ros1_bridge`:
* Packaging Linux [Build Status](http://ci.ros2.org/job/ci_packaging_linux/280/)

**Comment by dirk-thomas** [comment]
Depending on the answer of this question https://github.com/ros2/rmw_fastrtps/pull/342#issuecomment-574438327 this change should be considered for backporting.

**Comment by hidmic** [comment]
Hmm, `ros1_bridge` seems to exhibit segfaults when using `rmw_fastrtps_dynamic_cpp` only. I'll investigate.

**Comment by hidmic** [comment]
This is blocked until https://github.com/eclipse-cyclonedds/cyclonedds/issues/339 and https://github.com/ros2/rmw_fastrtps/issues/265 are finally addressed. Which leaves us in the same place we were at when this workaround was first introduced. I pinged eProsima and ADLINK folks, but we may as well close this until those fixes land.

**Comment by MiguelCompany** [comment]
> This is blocked until [eclipse-cyclonedds/cyclonedds#339](https://github.com/eclipse-cyclonedds/cyclonedds/issues/339) and [ros2/rmw_fastrtps#265](https://github.com/ros2/rmw_fastrtps/issues/265)

@hidmic I then suggest to change the title of this PR.

**Comment by hidmic** [comment]
> I then suggest to change the title of this PR.

Fair enough :)

**Comment by dirk-thomas** [comment]
I changed the title back since the patch knows nothing about CycloneDDS but only checks for FastRTPS.

**Comment by hidmic** [comment]
Oh, that's true. Silly me. I wonder why no one has run into this issue using CycloneDDS.

**Comment by dirk-thomas** [comment]
> I wonder why no one has run into this issue using CycloneDDS.

The test in the packaging job is failing with CycloneDDS for that reason.

**Pull request merged**
