### PR TITLE
Support for dynamic whitelisting bridge using regular expressions

### PR DESCRIPTION
**Pull request by dhananjaysathe**
Adds a new flavor of the bridge that supports adding a list of regular expressions as parameters to selectively and dynamically forward bridge topics/services.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Thank you for working on this feature. Why should the whitelisting be implemented in a separate executable rather than adding these options to the existing dynamic bridge? If none are specified the behavior would stay the same.

Also the added test might be good to separate into its own pull request to cover the existing dynamic bridge.

**Comment by dhananjaysathe** [comment]
Hey @dirk-thomas the bridge is a new executable called "dynamic_whitelist_bridge"  its similar sounding or named what led to the confusion i think .

**Comment by dirk-thomas** [comment]
My previous comment was asking *why* the whitelisting should be implemented in a separate executable. Why not add the feature to the *eixsting* executable `dynamic_bridge`?

**Comment by dhananjaysathe** [comment]
Ah i see let me chase this up next week

**Comment by dirk-thomas** [comment]
@dhananjaysathe Any update on this?

**Comment by claireyywang** [comment]
@dhananjaysathe friendly ping.

**Comment by dirk-thomas** [comment]
Closing due to no response. Please feel free to comment on the closed ticket and it can be reopened.

**Pull request closed without merging**
