### PR TITLE
Update apis

### PR DESCRIPTION
**Pull request by esteve**
This updates the bridge to use the `PublisherBase` / templated `Publisher` and the new version of `create_subscription`

### CODE REVIEW

**Comment by dirk-thomas** [comment]
LGTM

**Comment by dirk-thomas** [comment]
No squashing of (at least) commit 1 and 3?

**Comment by esteve** [comment]
It's already merged. I'll keep it in mind next time, but we agreed to squash if we felt like, though.

**Comment by dirk-thomas** [comment]
Well we decided on something more concrete: `Before merging a pull request all changes should be squashed into a small number semantic commits to keep the history clear.` (https://github.com/ros2/ros2/wiki/Developer-Guide#pull-requests).

**Comment by esteve** [comment]
Sounds good, but note the wording: should, not must, and it's at the discretion of the author of the PR. In any case, there's no point in pointing out that the changes weren't squashed right after merging.

**Pull request merged**
