### PR TITLE
Fix parameter bridge for topic if ros1 and ros2 type have a different name

### PR DESCRIPTION
**Pull request by cyrilleberger**
I have set ros1 type to "" since in create_bidirectional_bridge it can find out which type to use for ros1 when only specifying ros2 type.

An alternative fix would be to allow to specify different type for ros1 and ros2 in the parameters.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The message printed above provides misleading information now. Please update that accordingly.

**Comment by cyrilleberger** [comment]
Do you mean the commit message?

**Comment by dirk-thomas** [comment]
Sorry, I though I commented on a specific line. Without that context its not obvious. I was referring to the message printed a few lines above the change: line 69-72.

**Comment by cyrilleberger** [comment]
Is there anything else I need to change?

**Comment by dirk-thomas** [comment]
> Is there anything else I need to change?

Please comment after pushing additional commits to your PRs. Otherwise nobody gets a notification and it is unlikely someone will review the changes.

The change looks good to me. Thanks for the improvement.

**Comment by dirk-thomas** [comment]
[Build Status](https://ci.ros2.org/job/ci_packaging_linux/215/)

**Comment by dirk-thomas** [comment]
> [Build Status](https://ci.ros2.org/job/ci_packaging_linux/215/)

It seems like your fork is outdated which failed the CI build.

Testing a rebased version of your fork - the result looks good: [Build Status](https://ci.ros2.org/job/ci_packaging_linux/216/)

**Pull request merged**
