### PR TITLE
[WIP] Add GitHub actions

### PR DESCRIPTION
**Pull request by thomas-moulard**

### CODE REVIEW

**Comment by thomas-moulard** [comment]
* GH Actions are not triggered here - due to security concerns, running GH actions on PR the first time may be disabled. The same PR works fine on my fork: https://github.com/aws-ros-dev/ros1_bridge/pull/2

**Comment by dirk-thomas** [comment]
Since the PR has no description I would like to clarify the purpose of it. Is there goal to try out the new actions on a different repository or is the intention to get this merged in the near future?

Before merging actions to more repositories (then e.g. rosbag where is it being iterated on) I would like to see a more structured document what the goal is, what different use cases are being covered, discuss in a general location aspects like how often should it run, etc).

**Comment by thomas-moulard** [comment]
Hi Dirk, we'd like to get this merged in the future, but right now we are just trying to validate whether or not the approach would work. Due to the nature of CI, validation cannot be done locally, and I thought the actions were not running because it was a draft PR (it was not the case). We'll start discussing with the community, and have some kind of roadmap before actually submitting this PR for consideration.

**Comment by thomas-moulard** [comment]
Closing for now as the action aren't running on this repo anyway.

**Pull request closed without merging**
