### PR TITLE
Fix cpplint error

### PR DESCRIPTION
**Pull request by Blast545**
This should fix the linter errors on the rolling jobs:
https://ci.ros2.org/view/packaging/job/packaging_linux/2525/
https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/1877/
https://build.ros2.org/view/Rci/job/Rci__nightly-release_ubuntu_focal_amd64/569/

Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Seems reasonable to me, assuming ci_packaging CI is green.

**Review by fujitatomoya — APPROVED** [review]

**Comment by Blast545** [comment]
@clalancette I wanted to trigger a `ci_linux` job using the same parameters as the `packaging_linux` but the `ci_linux` one doesn't have the parameter `CI_MIXED_ROS_OVERLAY_PKGS` (where actually ros1_bridge is added).

What can I do to test this PR in this scenario?

**Comment by clalancette** [comment]
> What can I do to test this PR in this scenario?

You can trigger https://ci.ros2.org/job/ci_packaging_linux/ and https://ci.ros2.org/job/ci_packaging_linux-aarch64/

**Comment by Blast545** [comment]
@clalancette Oh, I didn't know about that one. Thanks!

`ci_packaging_linux` up to rcutils with cycloneDDS only (the error does not come from the ros2 environment, so it's not needed to build the whole thing)
[Build Status](https://ci.ros2.org/job/ci_packaging_linux/470/)

**Comment by Blast545** [comment]
I tested 3538f0f with `cpplint` locally, it should pass the CI test.

`ci_packaging_linux` up to ros1_bridge with cycloneDDS only
[Build Status](https://ci.ros2.org/job/ci_packaging_linux/471/)

**Comment by Blast545** [comment]
@ros-pull-request-builder retest this please

**Pull request merged**
