### PR TITLE
[forward port] update to use rosidl_parser and .idl files rather than rosidl_adapter and .msg files

### PR DESCRIPTION
**Pull request by wjwwood**
This is forward porting a change from Dashing made in https://github.com/ros2/ros1_bridge/pull/292 into master.

CI:

- `ci_packaging_linux`: [Build Status](https://ci.ros2.org/job/ci_packaging_linux/431/)

Once this one is merged, I'll backport it to Foxy and Eloquent.

closes https://github.com/ros2/ros1_bridge/issues/187

### CODE REVIEW

**Comment by wjwwood** [comment]
CI after fixing linting issue:

- [Build Status](https://ci.ros2.org/job/ci_packaging_linux/432/)

**Review by jacobperron — APPROVED** [review]
LGTM.

For backports, do you think we should address backwards compatibility concerns raised here https://github.com/ros2/ros1_bridge/pull/292#issuecomment-729889386 ?

**Comment by wjwwood** [comment]
> For backports, do you think we should address backwards compatibility concerns raised here #292 (comment) ?

It seems like we're ok leaving Dashing as-is there, so I assume the same is true for backports to other branches (e.g. foxy, eloquent), does that sound right? @jacobperron @sloretz 

Either way I think this is the right way for this to be done on master.

**Comment by jacobperron** [comment]
@wjwwood Friendly ping for a Foxy backport. I'm not sure if the ship has sailed for an Eloquent backport.

**Comment by wjwwood** [comment]
Yeah, I was waiting for the fix in https://github.com/ros2/ros1_bridge/pull/298.

**Pull request merged**
