### PR TITLE
Use rcpputils/scope_exit.hpp instead of rclcpp/scope_exit.hpp

### PR DESCRIPTION
**Pull request by christophebedard**
See https://github.com/ros2/rclcpp/pull/1727#issuecomment-901241040

Signed-off-by: Christophe Bedard <bedard.christophe@gmail.com>

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Looks reasonable to me with green CI.

**Comment by christophebedard** [comment]
I'm guessing GitHub CI is enough? Since `ros1_bridge` is seemingly always ignored by ci.ros2.org

**Comment by clalancette** [comment]
> I'm guessing GitHub CI is enough? Since `ros1_bridge` is seemingly always ignored by ci.ros2.org

You should be able to run the [ci_packaging](https://ci.ros2.org/job/ci_packaging_linux/) job, which builds the bridge.

**Comment by christophebedard** [comment]
> You should be able to run the [ci_packaging](https://ci.ros2.org/job/ci_packaging_linux/) job, which builds the bridge.

ah I see!

* Linux packaging [Build Status](https://ci.ros2.org/view/packaging/job/packaging_linux/2376/)

**Pull request merged**
